name: lint

on:
  push:
    branches: [ main ]
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r app/requirements.txt
        python -m pip install black pylint mypy
    - name: Format with black
      run: |
        black --diff --check $(git ls-files '*.py')

    - name: Lint with pylint
      run: |
        pylint --rc-file=setup.cfg app
