name: pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    uses: csbasil/gutenberg-api/.github/workflows/lint.yml@main

  test:
    name: test
    needs: lint
    uses: csbasil/gutenberg-api/.github/workflows/test.yml@main
