name: test

on:
  push:
    branches: [ main, development ]
  workflow_call:

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build docker stack
        run: docker compose --profile=pytest up -d
      - name: Test with pytest
        run: docker exec testapp pytest
      - name: Clean docker stack
        run: docker compose --profile=pytest down
